:source-highlighter: highlight.js
= ui patterns for the web

what problems does the ui solve?

The simplest thing a ui solves is to show some information to a reader. If the information doesn't change over time and if it is independent of the reader, a static html site is the best thing you can use.
Most websites in the internet are static websites, like blogposts, ads, documents, presentation sites.

But today we do not only want to show information, but also get information from the user. 

And then web apps also show, process and change the ui depending on the user. The user creates new information.  
As the expectations for a modern user interface rise, more sophisticated solutions are needed.

Modern user interfaces 
bla blub

why component frameworks?

== components
reuse solutions

divide and conquer

solid

testing???

why?

=== state management
decide as latest as possible

=== stateless components
why?
=== renderless components
why?

== collaboration 



--
- bazz
- foo
- bar
--

[source,javascript]
----
function foo(b) {
  const a = 10
  if (a + b > 10) {
    return 'some cool string'
  }
  throw new Error('UPPS')
}
----

ist das nicht cool
